apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: n4g0vodqu-nodejs 
  janus-idp.io/tekton: n4g0vodqu-nodejs
  backstage.io/kubernetes-id: n4g0vodqu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n4g0vodqu-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml